# 应用服务 WEB 访问端口
server:
  #自己ip
  ip:
  #开放端口
  port: 8085
# 应用名称
spring:
  application:
    name: Demo
#  redis:
#    ip: localhost
#    port: 6379
#    database: 0
  redis:
    #服务器地址
    host:
    #端口
    port: 6379
    #redis数据库
    database: 0
    #设置密码填空
    password:
  rabbitmq:
    #服务器地址
    host: 124.223.186.160
    #Mq端口
    port: 5672
    #默认用户密码
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3 #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）
# 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# 数据源名称
    name: defaultDataSource
  # 数据库连接地址
    url: jdbc:mysql://IP地址:端口/表名?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  # 数据库用户名&密码：
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    # 163邮箱的地址为smtp.163.com，直接填写即可
    host: smtp.163.com
    # 申请的邮箱
    username:
    # 注意密码是在开启smtp/pop3时自动生成的，记得保存一下，不然就找不到了
    password:

#sa-token:
#  # token 名称 (同时也是cookie名称)
#  token-name: satoken
#  # token 有效期，单位s 默认3天, -1代表永不过期
#  timeout: 259200
#  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
#  activity-timeout: -1
#  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
#  is-concurrent: false
#  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
#  is-share: false
#  # token风格
#  token-style: uuid
#  # 是否输出操作日志
#  is-log: false

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis-plus:
  mapper-locations: classpath:mapper/*xml
#  classpath*:/mapper/**/*Dao.xml
#指定Mybatis的实体目录
  type-aliases-package: com.pw.demo.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    #上传地址，推荐图床 或者服务器路径
    path:


#搜索模式
search:
  mode:

#上传模式
uploadLocal:
  mode:


#第三方配置信息
qq:
  app-id: QQAPPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={102010048}

weibo:
  app-id: 微博APPID
  app-secret: 微博APPSECRET
  grant-type: authorization_code
  redirect-url: 微博回调地址
  access-token-url: https://api.weibo.com/oauth2/access_token
  user-info-url: https://api.weibo.com/2/users/show.json?uid={uid}&access_token={access_token}



